
  export const GET_FUTSAL_GROUNDS_START = 'GET_FUTSAL_GROUNDS_START';
  export const GET_FUTSAL_GROUNDS_SUCCESS = 'GET_FUTSAL_GROUNDS_SUCCESS';
  export const GET_FUTSAL_GROUNDS_FAILURE = 'GET_FUTSAL_GROUNDS_FAILURE';
  
  
  export const GET_BOOKINGS_START = 'GET_BOOKINGS_START';
  export const GET_BOOKINGS_SUCCESS = 'GET_BOOKINGS_SUCCESS';
  export const GET_BOOKINGS_FAILURE = 'GET_BOOKINGS_FAILURE';
  
  export const UNRESERVE_BOOKING_START = 'UNRESERVE_BOOKING_START';
  export const UNRESERVE_BOOKING_SUCCESS = 'UNRESERVE_BOOKING_SUCCESS';
  export const UNRESERVE_BOOKING_FAILURE = 'UNRESERVE_BOOKING_FAILURE';
  
  export const RESERVE_BOOKING_START = 'RESERVE_BOOKING_START';
  export const RESERVE_BOOKING_SUCCESS = 'RESERVE_BOOKING_SUCCESS';
  export const RESERVE_BOOKING_FAILURE = 'RESERVE_BOOKING_FAILURE';
  
  
  export const RESET_BOOKING_LIST = 'RESET_BOOKING_LIST';
  
  export const GET_CURRENT_BOOKING = 'GET_CURRENT_BOOKING';